CREATE DATABASE IF NOT EXISTS Student;


USE Student;
CREATE TABLE IF NOT EXISTS marks (
    roll INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    id VARCHAR(50) NOT NULL,
    total FLOAT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;